name: Arduino CI

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
      - name: Lint code.
        uses: arduino/arduino-lint-action@v1
        with:
          compliance: specification
          library-manager: update
          official: true
          project-type: library